[package]
edition = "2021"
name = "stat_client"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = {version = "1", features = ["serde"]}
chrono = "0.4"
clap = {version = "3.0", features = ["derive"]}
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.5.4"
reqwest = {version = "0.11", features = ["rustls-tls"], default-features = false}
serde = {version = "1.0", default-features = false, features = ["derive", "alloc"]}
serde_json = {version = "1.0", default-features = false, features = ["alloc"]}
tokio = {version = "1", features = ["full"]}
